apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./edu/user/deployment.yaml
- ./edu/user/ingress.yaml
- ./edu/user/service.yaml
- ./edu/user/hpa.yaml
- ./edu/user/configmap.yaml
- ./edu/goods/deployment.yaml
- ./edu/goods/ingress.yaml
- ./edu/goods/service.yaml
- ./edu/goods/hpa.yaml
images:
- name: hmschlng/
- name: hmschlng/edu-goods
- name: hmschlng/edu-user
